{
 "title": "Shopmate-dashboard",
 "time": { "from": "2025-08-21T03:48:03.579Z", "to": "2025-08-21T05:43:13.841Z" },
 "panels": [
  {
   "title": "ECS Service Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "shopmate-dev", "ServiceName": "shopmate-service-dev" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ECS Service CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "shopmate-dev", "ServiceName": "shopmate-service-dev" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Stress Load req/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{route=\"/stress\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Individual Container CPU%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(nodejs_process_cpu_seconds_total[30s]) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 7 },
   "targets": [
    {
     "dimensions": { "ClusterName": "shopmate-dev", "ServiceName": "shopmate-service-dev" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  }
 ]
}